export class ResManager {
  // 颜色
  static EC_MAIN_COLOR = $r('app.color.ec_main_color')
  static EC_SUB_BLUE = $r('app.color.ec_sub_blue')
  static EC_SUB_GREEN = $r('app.color.ec_sub_green')
  static EC_SUB_YELLOW = $r('app.color.ec_sub_yellow')
  static EC_SUB_RED = $r('app.color.ec_sub_red')
  static EC_MID_19 = $r('app.color.ec_mid_19')
  static EC_MID_59 = $r('app.color.ec_mid_59')
  static EC_MID_99 = $r('app.color.ec_mid_99')
  static EC_MID_WHITE = $r('app.color.ec_mid_white')
  static EC_MID_BLACK = $r('app.color.ec_mid_black')
  static EC_MID_BG = $r('app.color.ec_mid_bg')
  static EC_MID_LINE = $r('app.color.ec_mid_line')
  // 字体
  static EC_CONTENT_SPACE = $r('app.float.ec_content_space')
  static EC_MICRO_FS = $r('app.float.ec_micro_font_size')
  static EC_BIG_TITLE_FS = $r('app.float.ec_big_title_font_size')
  static EC_PAGE_TITLE_FS = $r('app.float.ec_page_title_font_size')
  static EC_MODULE_TITLE_FS = $r('app.float.ec_module_title_font_size')
  static EC_NORMAL_FS = $r('app.float.ec_normal_font_size')
  static EC_CARD_FS = $r('app.float.ec_card_font_size')
  static EC_SMALL_FS = $r('app.float.ec_small_font_size')
  static EC_NORMAL_RD = $r('app.float.ec_normal_radius')
  // 图片
  static IC_LOGO = $r('app.media.icon')
  static IC_ARROW_UP = $r('app.media.ic_arrow_up')
  static IC_BACK_BLACK = $r('app.media.ic_back_black')
  static IC_BACK_WHITE = $r('app.media.ic_back_white')
  static IC_DOWN = $r("app.media.ic_time_down")
  static IC_FJSB_SS = $r('app.media.ic_fjsb_ss')
  static IC_HUAWEI = $r('app.media.ic_huawei')
  static IC_JRWZ_GX = $r('app.media.ic_jrwz_gx')
  static IC_MJPW_WIFI = $r('app.media.ic_mjpw_wifi')
  static IC_SBAZ_XQ = $r('app.media.ic_sbaz_xq')
  static IC_SBBD_LY = $r('app.media.ic_sbbd_ly')
  static IC_WOD_DEL = $r('app.media.ic_wode_delete')
  static IC_PROD_DOOR = $r('app.media.img_shebei_mj')
  static IC_PROD_BLOOD = $r('app.media.img_shebei_xt')
  static IC_PROD_WATCH = $r('app.media.img_shebei_sb')
  // 间距
  static SIZE_GUTTER_LG = 15
  static SIZE_GUTTER_MD = 10
  static SIZE_GUTTER_SM = 5
}
